WordRepositoryFake.kt was added to androidTest, This will be used to load fake database.
Bug when running the MainActivityTest.kt.
java.lang.NoSuchMethodError: No static method loadSingleServiceOrNull(Ljava/lang/Class;)Ljava/lang/Object; in class